### ISSUE TITLE
Don´t migrate 

### ISSUE THREAD

**Issue by D1Alexandre** [nakagami/djfirebirdsql#4]
I have the latest version 0.2.0, but I can't run migrate, so I get the following error.

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, filiais, sessions
Running migrations:
Traceback (most recent call last):
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 84, in
_execute
    return self.cursor.execute(sql)
  File "C:\python37\lib\site-packages\djfirebirdsql\cursor.py", line 66, in exec
ute
    super().execute(self.query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 308, in execu
te
    stmt = self._get_stmt(query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 295, in _get_
stmt
    stmt.prepare(query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 153, in prepa
re
    (h, oid, buf) = self.trans.connection._op_response()
  File "C:\python37\lib\site-packages\firebirdsql\wireprotocol.py", line 1094, i
n _op_response
    return self._parse_op_response()
  File "C:\python37\lib\site-packages\firebirdsql\wireprotocol.py", line 298, in
 _parse_op_response
    raise OperationalError(message, gds_codes, sql_code)
firebirdsql.OperationalError: Dynamic SQL Error
SQL error code = -104
Token unknown - line 1, column 58
b'by'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\python37\lib\site-packages\django\db\migrations\recorder.py", line 67
, in ensure_schema
    editor.create_model(self.Migration)
  File "C:\python37\lib\site-packages\django\db\backends\base\schema.py", line 3
24, in create_model
    self.execute(sql, params or None)
  File "C:\python37\lib\site-packages\djfirebirdsql\schema.py", line 24, in exec
ute
    super().execute(query, params)
  File "C:\python37\lib\site-packages\django\db\backends\base\schema.py", line 1
42, in execute
    cursor.execute(sql, params)
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 100, in
 execute
    return super().execute(sql, params)
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 68, in
execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._e
xecute)
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 77, in
_execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 86, in
_execute
    return self.cursor.execute(sql, params)
  File "C:\python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\python37\lib\site-packages\django\db\backends\utils.py", line 84, in
_execute
    return self.cursor.execute(sql)
  File "C:\python37\lib\site-packages\djfirebirdsql\cursor.py", line 66, in exec
ute
    super().execute(self.query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 308, in execu
te
    stmt = self._get_stmt(query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 295, in _get_
stmt
    stmt.prepare(query)
  File "C:\python37\lib\site-packages\firebirdsql\fbcore.py", line 153, in prepa
re
    (h, oid, buf) = self.trans.connection._op_response()
  File "C:\python37\lib\site-packages\firebirdsql\wireprotocol.py", line 1094, i
n _op_response
    return self._parse_op_response()
  File "C:\python37\lib\site-packages\firebirdsql\wireprotocol.py", line 298, in
 _parse_op_response
    raise OperationalError(message, gds_codes, sql_code)
django.db.utils.OperationalError: ("Dynamic SQL Error\nSQL error code = -104\nTo
ken unknown - line 1, column 58\nb'by'\n", -104)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\python37\lib\site-packages\django\core\management\__init__.py", line
401, in execute_from_command_line
    utility.execute()
  File "C:\python37\lib\site-packages\django\core\management\__init__.py", line
395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\python37\lib\site-packages\django\core\management\base.py", line 328,
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\python37\lib\site-packages\django\core\management\base.py", line 369,
 in execute
    output = self.handle(*args, **options)
  File "C:\python37\lib\site-packages\django\core\management\base.py", line 83,
in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\python37\lib\site-packages\django\core\management\commands\migrate.py
", line 233, in handle
    fake_initial=fake_initial,
  File "C:\python37\lib\site-packages\django\db\migrations\executor.py", line 91
, in migrate
    self.recorder.ensure_schema()
  File "C:\python37\lib\site-packages\django\db\migrations\recorder.py", line 69
, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (
%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the dja
ngo_migrations table (("Dynamic SQL Error\nSQL error code = -104\nToken unknown
- line 1, column 58\nb'by'\n", -104))

**Comment by nakagami** [comment]
You need Firebird 4.0 (at least 3.0).

If you use Firebird 2.5, Please check django-firebird

**Comment by mariuz** [comment]
I have added a notice about Firebird 3.0 in the readme 
https://github.com/nakagami/djfirebirdsql/pull/5
